# Generated by Django 3.0.4 on 2020-04-30 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='namel',
        ),
    ]
