# Generated by Django 3.0.4 on 2020-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_contact_namel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pice',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=300),
        ),
    ]
